version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume: